[tool.pysen]
version = "0.9"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 88
py_version = "py37"
isort_known_first_party = ["deep_table"]

[[tool.pysen.lint.mypy_targets]]
  paths = ["."]
